#
#   This is the application-git configuration for a configuration service.  
#          
#       -  A configuraton service that uses a git-based repository to read the files from.
#         
#
####################################
# Server git solution
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        #encrypt.enabled: true
        encrypt.enabled: false
        git:
          uri: https://github.com/matsunily/config-server-repo/
          searchPaths: assetsservice,organizationservice
          username: matsunily
          password: SFglobal#82
